# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- deploy

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  projectPath: '**/src/Api'
  project: '$(projectPath)/DeviceManagement.Api.csproj'

  tests: '**/*.Tests.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: DotNetBuild
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: windows-latest
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core 6 sdk'
      inputs:
        version: '6.0.x'
    - task: NuGetToolInstaller@1
      displayName: 'NuGet Install'
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '$(solution)'
      displayName: 'dotnet Restore'
    - task: DotNetCoreCLI@2
      inputs:
        command: build
        projects: '$(project)'
        arguments: '-c $(buildConfiguration)'
      displayName: 'Build API Project'
    - task: DotNetCoreCLI@2
      inputs:
        command: test
        publishTestResults: true
        projects: '$(tests)'
      displayName: 'Run Tests'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '-o $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: false
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: '$(buildConfiguration)'
        publishLocation: 'Container'
- stage: DockerBuild
  displayName: Build docker image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'meshtmscontainerregistry'
        repository: 'devicemanagement'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'